### PR TITLE
Update from bitcoin v23.2 to v24.1

### PR DESCRIPTION
**Pull request by muxator**
This is an experimental attempt at migrating the code base from bitcoin **v23.2** to **v24.1**.

What works:
- the main application builds
  ```
  $ bin/bitcoind --version
  Itcoin Core version v24.1.0-itcoin-1
  Copyright (C) 2019-2022 Bank of Italy
  Copyright (C) 2009-2022 The Bitcoin Core developers
  ```
- the C++ tests build
- almost all the C++ tests pass

What still does not work:
- 2 C++ tests fail:
  ```
  wallet/test/spend_tests.cpp(152): error: in "spend_tests/wallet_duplicated_preset_inputs_test": check !res_tx.has_value() has failed
  2023-05-25T17:29:43.334683Z (mocktime: 2020-08-31T15:34:12Z) [test] [wallet/coinselection.cpp:320] [KnapsackSolver] [selectcoins] Coin selection best subset: 50.00 50.00 50.00 total 150.00
  2023-05-25T17:29:43.347933Z (mocktime: 2020-08-31T15:34:12Z) [test] [wallet/wallet.h:832] [WalletLogPrintf] [default wallet] Fee Calculation: Fee:0 Bytes:750 Tgt:0 (requested 6) Reason:"Fallback fee" Decay 0.00000: Estimation: (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out) Fail: (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out)
  wallet/test/spend_tests.cpp(157): error: in "spend_tests/wallet_duplicated_preset_inputs_test": check !res_tx.has_value() has failed
  2023-05-25T17:29:43.352638Z (mocktime: 2020-08-31T15:34:12Z) [scheduler] [util/thread.cpp:22] [TraceThread] scheduler thread exit
  ```
- ~~`infra/initialize-itcoin-local.sh` fails because the call `do_generate_next_block()` in `miner` raises a `NotImplementedError` due to a bad merge~~ **edit**: this is fixed now
- the functional test suite fails

### CODE REVIEW

**Comment by muxator** [comment]
v2:
- `infra/initialize_itcoin_local.sh` (and thus `contrib/signet/miner`) is now working

Running the functional test suite right now.

**Comment by muxator** [comment]
v3:

Fixed `mempool_spend_coinbase`.

Current test status:

```
$ ./test_runner.py feature_coinstatsindex.py rpc_psbt.py rpc_signrawtransactionwithkey.py wallet_send.py wallet_signrawtransactionwithwallet.py

[... details follow ...]

TEST                                                   | STATUS    | DURATION

feature_coinstatsindex.py                              | ✖ Failed  | 4 s
rpc_psbt.py --descriptors                              | ✖ Failed  | 3 s
rpc_psbt.py --legacy-wallet                            | ✖ Failed  | 2 s
rpc_signrawtransactionwithkey.py                       | ✖ Failed  | 3 s
wallet_send.py --descriptors                           | ✖ Failed  | 9 s
wallet_send.py --legacy-wallet                         | ✖ Failed  | 9 s
wallet_signrawtransactionwithwallet.py --descriptors   | ✖ Failed  | 4 s
wallet_signrawtransactionwithwallet.py --legacy-wallet | ✖ Failed  | 4 s

ALL                                                    | ✖ Failed  | 38 s (accumulated) 
Runtime: 12 s
```

Details of running the failing tests:

```
Temporary test directory at /tmp/test_runner_₿_🏃_20230526_155406
Running Unit Tests for Test Framework Modules
..........
----------------------------------------------------------------------
Ran 10 tests in 0.854s

OK
1/8 - rpc_psbt.py --legacy-wallet failed, Duration: 2 s

stdout:
2023-05-26T13:54:09.091000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230526_155406/rpc_psbt_6
2023-05-26T13:54:10.653000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "<base>/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "<base>/test/functional/rpc_psbt.py", line 123, in run_test
    assert_equal(len(self.nodes[0].decodepsbt(psbtx1)['tx']['vin']), 2)
  File "<base>/test/functional/test_framework/util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(3 == 2)
2023-05-26T13:54:10.705000Z TestFramework (INFO): Stopping nodes
2023-05-26T13:54:10.813000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230526_155406/rpc_psbt_6
2023-05-26T13:54:10.813000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230526_155406/rpc_psbt_6/test_framework.log
2023-05-26T13:54:10.813000Z TestFramework (ERROR): 
2023-05-26T13:54:10.814000Z TestFramework (ERROR): Hint: Call <base>/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230526_155406/rpc_psbt_6' to consolidate all logs
2023-05-26T13:54:10.814000Z TestFramework (ERROR): 
2023-05-26T13:54:10.814000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-05-26T13:54:10.814000Z TestFramework (ERROR): https://github.com/bancaditalia/itcoin-core/issues
2023-05-26T13:54:10.815000Z TestFramework (ERROR): 


stderr:


2/8 - rpc_psbt.py --descriptors failed, Duration: 3 s

stdout:
2023-05-26T13:54:09.093000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230526_155406/rpc_psbt_5
2023-05-26T13:54:11.094000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "<base>/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "<base>/test/functional/rpc_psbt.py", line 123, in run_test
    assert_equal(len(self.nodes[0].decodepsbt(psbtx1)['tx']['vin']), 2)
  File "<base>/test/functional/test_framework/util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(3 == 2)
2023-05-26T13:54:11.148000Z TestFramework (INFO): Stopping nodes
2023-05-26T13:54:11.259000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230526_155406/rpc_psbt_5
2023-05-26T13:54:11.260000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230526_155406/rpc_psbt_5/test_framework.log
2023-05-26T13:54:11.260000Z TestFramework (ERROR): 
2023-05-26T13:54:11.260000Z TestFramework (ERROR): Hint: Call <base>/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230526_155406/rpc_psbt_5' to consolidate all logs
2023-05-26T13:54:11.260000Z TestFramework (ERROR): 
2023-05-26T13:54:11.261000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-05-26T13:54:11.261000Z TestFramework (ERROR): https://github.com/bancaditalia/itcoin-core/issues
2023-05-26T13:54:11.261000Z TestFramework (ERROR): 


stderr:


3/8 - rpc_signrawtransactionwithkey.py failed, Duration: 3 s

stdout:
2023-05-26T13:54:09.081000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230526_155406/rpc_signrawtransactionwithkey_4
2023-05-26T13:54:09.942000Z TestFramework (INFO): Test valid raw transaction with one input
2023-05-26T13:54:09.956000Z TestFramework (INFO): Test signing transaction to P2SH-P2WSH addresses without wallet
2023-05-26T13:54:12.062000Z TestFramework (INFO): Test with a P2PKH script as the witnessScript
2023-05-26T13:54:12.071000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "<base>/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "<base>/test/functional/rpc_signrawtransactionwithkey.py", line 136, in run_test
    self.witness_script_test()
  File "<base>/test/functional/rpc_signrawtransactionwithkey.py", line 107, in witness_script_test
    self.verify_txn_with_witness_script(tx_type)
  File "<base>/test/functional/rpc_signrawtransactionwithkey.py", line 123, in verify_txn_with_witness_script
    txid = self.send_to_address(addr, 10)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base>/test/functional/rpc_signrawtransactionwithkey.py", line 43, in send_to_address
    input = {"txid": self.nodes[0].getblock(self.block_hash[self.blk_idx])["tx"][0], "vout": 0}
                                            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range
2023-05-26T13:54:12.123000Z TestFramework (INFO): Stopping nodes
2023-05-26T13:54:12.176000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230526_155406/rpc_signrawtransactionwithkey_4
2023-05-26T13:54:12.177000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230526_155406/rpc_signrawtransactionwithkey_4/test_framework.log
2023-05-26T13:54:12.177000Z TestFramework (ERROR): 
2023-05-26T13:54:12.177000Z TestFramework (ERROR): Hint: Call <base>/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230526_155406/rpc_signrawtransactionwithkey_4' to consolidate all logs
2023-05-26T13:54:12.177000Z TestFramework (ERROR): 
2023-05-26T13:54:12.177000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-05-26T13:54:12.177000Z TestFramework (ERROR): https://github.com/bancaditalia/itcoin-core/issues
2023-05-26T13:54:12.177000Z TestFramework (ERROR): 


stderr:


4/8 - feature_coinstatsindex.py failed, Duration: 4 s

stdout:
2023-05-26T13:54:09.077000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230526_155406/feature_coinstatsindex_7
2023-05-26T13:54:11.261000Z TestFramework (INFO): Test that gettxoutsetinfo() output is consistent with or without coinstatsindex option
2023-05-26T13:54:11.276000Z TestFramework (INFO): Test that gettxoutsetinfo() can get fetch data on specific heights with index
2023-05-26T13:54:11.933000Z TestFramework (INFO): Test gettxoutsetinfo() with index and verbose flag
2023-05-26T13:54:12.171000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "<base>/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "<base>/test/functional/feature_coinstatsindex.py", line 51, in run_test
    self._test_coin_stats_index()
  File "<base>/test/functional/feature_coinstatsindex.py", line 170, in _test_coin_stats_index
    assert_equal(res6['block_info'], {
  File "<base>/test/functional/test_framework/util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not({'prevout_spent': Decimal('70.99968800'), 'coinbase': Decimal('50.01001000'), 'new_outputs_ex_coinbase': Decimal('49.99967800'), 'unspendable': Decimal('20.99000000'), 'unspendables': {'genesis_block': Decimal('0E-8'), 'bip30': Decimal('0E-8'), 'scripts': Decimal('20.99000000'), 'unclaimed_rewards': Decimal('0E-8')}} == {'unspendable': Decimal('20.99000000'), 'prevout_spent': Decimal('111.00004440'), 'new_outputs_ex_coinbase': Decimal('89.99998060'), 'coinbase': Decimal('50.01001000'), 'unspendables': {'genesis_block': Decimal('0E-8'), 'bip30': Decimal('0E-8'), 'scripts': Decimal('20.99000000'), 'unclaimed_rewards': Decimal('0E-8')}})
2023-05-26T13:54:12.222000Z TestFramework (INFO): Stopping nodes
2023-05-26T13:54:12.326000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230526_155406/feature_coinstatsindex_7
2023-05-26T13:54:12.326000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230526_155406/feature_coinstatsindex_7/test_framework.log
2023-05-26T13:54:12.326000Z TestFramework (ERROR): 
2023-05-26T13:54:12.326000Z TestFramework (ERROR): Hint: Call <base>/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230526_155406/feature_coinstatsindex_7' to consolidate all logs
2023-05-26T13:54:12.326000Z TestFramework (ERROR): 
2023-05-26T13:54:12.326000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-05-26T13:54:12.326000Z TestFramework (ERROR): https://github.com/bancaditalia/itcoin-core/issues
2023-05-26T13:54:12.327000Z TestFramework (ERROR): 


stderr:


Remaining jobs: [wallet_send.py --legacy-wallet, wallet_send.py --descriptors, wallet_signrawtransactionwithwallet.py --legacy-wallet, wallet_signrawtransactionwithwallet.py --descriptors]
5/8 - wallet_signrawtransactionwithwallet.py --legacy-wallet failed, Duration: 4 s

stdout:
2023-05-26T13:54:12.494000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230526_155406/wallet_signrawtransactionwithwallet_1
2023-05-26T13:54:13.192000Z TestFramework (INFO): Test script verification errors
2023-05-26T13:54:13.216000Z TestFramework (INFO): Test OP_1NEGATE (0x4f) satisfies BIP62 minimal push standardness rule
2023-05-26T13:54:13.220000Z TestFramework (INFO): Test correct error reporting when trying to sign a locked output
2023-05-26T13:54:13.591000Z TestFramework (INFO): Test signing a fully signed transaction does nothing
2023-05-26T13:54:14.739000Z TestFramework (INFO): Test signing a transaction containing a fully signed CSV input
2023-05-26T13:54:15.959000Z TestFramework (INFO): Test signing a transaction containing a fully signed CLTV input
2023-05-26T13:54:16.129000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "<base>/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "<base>/test/functional/wallet_signrawtransactionwithwallet.py", line 301, in run_test
    self.test_signing_with_cltv()
  File "<base>/test/functional/wallet_signrawtransactionwithwallet.py", line 242, in test_signing_with_cltv
    assert_equal(signed["complete"], True)
  File "<base>/test/functional/test_framework/util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(False == True)
2023-05-26T13:54:16.181000Z TestFramework (INFO): Stopping nodes
2023-05-26T13:54:16.234000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230526_155406/wallet_signrawtransactionwithwallet_1
2023-05-26T13:54:16.234000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230526_155406/wallet_signrawtransactionwithwallet_1/test_framework.log
2023-05-26T13:54:16.234000Z TestFramework (ERROR): 
2023-05-26T13:54:16.234000Z TestFramework (ERROR): Hint: Call <base>/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230526_155406/wallet_signrawtransactionwithwallet_1' to consolidate all logs
2023-05-26T13:54:16.235000Z TestFramework (ERROR): 
2023-05-26T13:54:16.235000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-05-26T13:54:16.235000Z TestFramework (ERROR): https://github.com/bancaditalia/itcoin-core/issues
2023-05-26T13:54:16.235000Z TestFramework (ERROR): 


stderr:


Remaining jobs: [wallet_send.py --legacy-wallet, wallet_send.py --descriptors, wallet_signrawtransactionwithwallet.py --descriptors]
6/8 - wallet_signrawtransactionwithwallet.py --descriptors failed, Duration: 4 s

stdout:
2023-05-26T13:54:12.975000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230526_155406/wallet_signrawtransactionwithwallet_0
2023-05-26T13:54:13.702000Z TestFramework (INFO): Test script verification errors
2023-05-26T13:54:13.711000Z TestFramework (INFO): Test OP_1NEGATE (0x4f) satisfies BIP62 minimal push standardness rule
2023-05-26T13:54:13.713000Z TestFramework (INFO): Test correct error reporting when trying to sign a locked output
2023-05-26T13:54:14.117000Z TestFramework (INFO): Test signing a fully signed transaction does nothing
2023-05-26T13:54:15.295000Z TestFramework (INFO): Test signing a transaction containing a fully signed CSV input
2023-05-26T13:54:16.544000Z TestFramework (INFO): Test signing a transaction containing a fully signed CLTV input
2023-05-26T13:54:16.759000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "<base>/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "<base>/test/functional/wallet_signrawtransactionwithwallet.py", line 301, in run_test
    self.test_signing_with_cltv()
  File "<base>/test/functional/wallet_signrawtransactionwithwallet.py", line 242, in test_signing_with_cltv
    assert_equal(signed["complete"], True)
  File "<base>/test/functional/test_framework/util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(False == True)
2023-05-26T13:54:16.811000Z TestFramework (INFO): Stopping nodes
2023-05-26T13:54:16.917000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230526_155406/wallet_signrawtransactionwithwallet_0
2023-05-26T13:54:16.917000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230526_155406/wallet_signrawtransactionwithwallet_0/test_framework.log
2023-05-26T13:54:16.918000Z TestFramework (ERROR): 
2023-05-26T13:54:16.918000Z TestFramework (ERROR): Hint: Call <base>/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230526_155406/wallet_signrawtransactionwithwallet_0' to consolidate all logs
2023-05-26T13:54:16.918000Z TestFramework (ERROR): 
2023-05-26T13:54:16.918000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-05-26T13:54:16.918000Z TestFramework (ERROR): https://github.com/bancaditalia/itcoin-core/issues
2023-05-26T13:54:16.919000Z TestFramework (ERROR): 


stderr:


Remaining jobs: [wallet_send.py --legacy-wallet, wallet_send.py --descriptors]
7/8 - wallet_send.py --legacy-wallet failed, Duration: 9 s

stdout:
2023-05-26T13:54:11.525000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230526_155406/wallet_send_3
2023-05-26T13:54:12.283000Z TestFramework (INFO): Setup wallets...
2023-05-26T13:54:13.845000Z TestFramework (INFO): Send to address...
2023-05-26T13:54:15.954000Z TestFramework (INFO): Don't broadcast...
2023-05-26T13:54:16.035000Z TestFramework (INFO): Return PSBT...
2023-05-26T13:54:16.083000Z TestFramework (INFO): Create transaction that spends to address, but don't broadcast...
2023-05-26T13:54:16.247000Z TestFramework (INFO): Create PSBT from watch-only wallet w3, sign with w2...
2023-05-26T13:54:16.270000Z TestFramework (INFO): Create PSBT from wallet w4 with watch-only keys, sign with w2...
2023-05-26T13:54:16.299000Z TestFramework (INFO): Create OP_RETURN...
2023-05-26T13:54:17.510000Z TestFramework (INFO): Test setting explicit fee rate
2023-05-26T13:54:18.779000Z TestFramework (INFO): Explicit fee rate raises RPC error 'fee rate too low' if fee_rate of 0.99999999 is passed
2023-05-26T13:54:18.833000Z TestFramework (INFO): Explicit fee rate raises if invalid fee_rate is passed
2023-05-26T13:54:19.910000Z TestFramework (INFO): If inputs are specified, do not automatically add more...
2023-05-26T13:54:20.066000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "<base>/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "<base>/test/functional/wallet_send.py", line 411, in run_test
    assert_equal(utxo1["amount"], 50)
  File "<base>/test/functional/test_framework/util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(25.00004380 == 50)
2023-05-26T13:54:20.120000Z TestFramework (INFO): Stopping nodes
2023-05-26T13:54:20.225000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230526_155406/wallet_send_3
2023-05-26T13:54:20.225000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230526_155406/wallet_send_3/test_framework.log
2023-05-26T13:54:20.225000Z TestFramework (ERROR): 
2023-05-26T13:54:20.226000Z TestFramework (ERROR): Hint: Call <base>/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230526_155406/wallet_send_3' to consolidate all logs
2023-05-26T13:54:20.226000Z TestFramework (ERROR): 
2023-05-26T13:54:20.226000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-05-26T13:54:20.226000Z TestFramework (ERROR): https://github.com/bancaditalia/itcoin-core/issues
2023-05-26T13:54:20.226000Z TestFramework (ERROR): 


stderr:


Remaining jobs: [wallet_send.py --descriptors]
8/8 - wallet_send.py --descriptors failed, Duration: 9 s

stdout:
2023-05-26T13:54:11.980000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230526_155406/wallet_send_2
2023-05-26T13:54:12.970000Z TestFramework (INFO): Setup wallets...
2023-05-26T13:54:14.460000Z TestFramework (INFO): Send to address...
2023-05-26T13:54:15.681000Z TestFramework (INFO): Don't broadcast...
2023-05-26T13:54:15.773000Z TestFramework (INFO): Return PSBT...
2023-05-26T13:54:15.860000Z TestFramework (INFO): Create transaction that spends to address, but don't broadcast...
2023-05-26T13:54:16.118000Z TestFramework (INFO): Create PSBT from watch-only wallet w3, sign with w2...
2023-05-26T13:54:16.148000Z TestFramework (INFO): Create OP_RETURN...
2023-05-26T13:54:17.343000Z TestFramework (INFO): Test setting explicit fee rate
2023-05-26T13:54:18.738000Z TestFramework (INFO): Explicit fee rate raises RPC error 'fee rate too low' if fee_rate of 0.99999999 is passed
2023-05-26T13:54:18.819000Z TestFramework (INFO): Explicit fee rate raises if invalid fee_rate is passed
2023-05-26T13:54:20.180000Z TestFramework (INFO): If inputs are specified, do not automatically add more...
2023-05-26T13:54:20.336000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "<base>/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "<base>/test/functional/wallet_send.py", line 411, in run_test
    assert_equal(utxo1["amount"], 50)
  File "<base>/test/functional/test_framework/util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(25.00004380 == 50)
2023-05-26T13:54:20.391000Z TestFramework (INFO): Stopping nodes
2023-05-26T13:54:20.549000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230526_155406/wallet_send_2
2023-05-26T13:54:20.549000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230526_155406/wallet_send_2/test_framework.log
2023-05-26T13:54:20.549000Z TestFramework (ERROR): 
2023-05-26T13:54:20.550000Z TestFramework (ERROR): Hint: Call <base>/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230526_155406/wallet_send_2' to consolidate all logs
2023-05-26T13:54:20.550000Z TestFramework (ERROR): 
2023-05-26T13:54:20.550000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-05-26T13:54:20.550000Z TestFramework (ERROR): https://github.com/bancaditalia/itcoin-core/issues
2023-05-26T13:54:20.550000Z TestFramework (ERROR): 


stderr:
```

**Comment by muxator** [comment]
Now that all the bitcoin tests are working (thanks @giuseppegalano-bi), and that https://github.com/bancaditalia/secp256k1-frost/pull/3 is proceding well (@matteonardelli), here's a **v4**:

- rewritten the history compacting the churn on the initial merge commit and on a C++ test
- vendorized https://github.com/bancaditalia/secp256k1-frost/commit/265a693d34fabb7b5388df37cfd668529441bd8b so that itcoin-fbft should now work with the itcoin-core version from this PR

If the integration works, a v5 will be needed.

**Comment by muxator** [comment]
**v5**:
- rewritten the log putting [secp256k1-frost 0.1.0-frost-1](https://github.com/bancaditalia/secp256k1-frost/tree/1c6750fdf497d6b31f8c73c1410fb3896b80fa4d) at the start
- tested on ubuntu 22.04 with gcc 11 and gcc 12 (`make check` and `test/functional/test_runner.py`)

Ready in my opinion.

**Comment by giuseppegalano-bi** [comment]
It looks okay to me

**Comment by muxator** [comment]
#10 is exposing a potential flakiness in the current test suite.

Pausing the integration of this series until we have better information there.

**Comment by muxator** [comment]
Rebased on top of the test fixes (#12) and (#13).

Integrating.
